defaults:
  - _self_

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d/%H-%M-%S}

random_state: 42

dataset:
  _target_: torch_geometric.datasets.Planetoid
  root: ${hydra:runtime.cwd}/data
  name: Cora

perturbation:
  method: remove_edges
  params:
    probability: 0.9